### ISSUE TITLE
Setup issue with 2024.8.0b0 

### ISSUE THREAD

**Issue by TheZoker** [mvdwetering/huesyncbox#113]
**Describe the bug**
Since updating to 2024.8.0b0 beta of Home Assistant, the Hue Sync Box was unavailable.
I then removed the integration and re-added it, but I was not able to add the box. It tells me to press the button, but even after pressing it, nothing happens. There where a lot of changed regarding aiohttp. So maybe there is an issue?
BTW the box still gets discovered by HA, but connection seems to be broken. 

**To Reproduce**
1. Update to HA 2024.8.0b0 
2. Try to setup Hue Sync Box

**Expected behavior**
Setup

**Diagnostics**
If possible add diagnostics data from HA. The "Download diagnostics" option can be found in the vertical 3 dots menu (⋮) of the integration.

I can't setup the integration so I don't have diagnostics logs :/ 

**Logging**
No logs in HA :/

**Environment**
Provide details about the versions you are using, which helps to reproduce and find the issue quicker.

- Home Assistant Core version: 2024.8.0b0 
- Home Assistant operating environment (OS/Container/Supervised/Core): OS
- Huesyncbox integration version:  2.2.2
- Last working version (if known): ?

**Additional info**
Add any other info about the problem here.

**Comment by mvdwetering** [comment]
I can reproduce and it indeed starts happening after updating to aiohttp 3.10.

It is due to the way I do the certificate verification which is a bit hacky. It seems that aiohttp has proper support for this since 3.9 so I will need to rework the connection logic a bit to change from my hacky version to the official one.

Will try to get an updated version out asap.

**Comment by TheZoker** [comment]
Thanks for the quick response!
I always use the beta, so if I notice any issue in the future again in beta (or in general) I'll let you know :)

**Comment by TheZoker** [comment]
And please let me know if I should test anything

**Comment by mvdwetering** [comment]
Version 2.2.3 has been release to address this issue

**Comment by TheZoker** [comment]
Works 🎉
