### ISSUE TITLE
Broken with 2024.8

### ISSUE THREAD

**Issue by connelhooley** [mvdwetering/huesyncbox#116]
**Describe the bug**
After upgrading to 2024.8 HA can no longer connect to my sync box:

![Screenshot 2024-08-07 212933](https://github.com/user-attachments/assets/0e28aa85-7ab6-4649-b335-5aa64897a6ab)

Reverting back to 2024.7 fixes the issue straight away 

**To Reproduce**
Upgrade to 2024.8
Go into integration in settings.
There will be an error.

**Expected behavior**
Extension should continue to work

**Environment**
Provide details about the versions you are using, which helps to reproduce and find the issue quicker.

- Home Assistant Core version: 2024.8
- Home Assistant operating environment (OS/Container/Supervised/Core): Container
- Huesyncbox integration version: 2.0.0
- Last working version (if known): 2.0.0

**Additional info**
2024.8 was literally just released so it's possible the HA core team have a bug they need to fix but I thought I'd raise an issue as a heads-up just in-case there's any actions required on your side.

**Comment by connelhooley** [comment]
I've asked on the HA discord:
https://discord.com/channels/330944238910963714/672220541343760384/1270844564864761947

It seems like there might be other extensions that failing for other users:
![image](https://github.com/user-attachments/assets/54c51c7c-6383-432f-ae01-b7bad2e4dd06)

**Comment by mvdwetering** [comment]
That has been fixed a few days ago. Update the integration to 2.2.3 (or higher)
