### ISSUE TITLE
Cannot complete integration

### ISSUE THREAD

**Issue by Resinchem** [mvdwetering/huesyncbox#13]
Installed via HACS and restarted Home Assistant (0.117.4).  New device automatically discovered just fine.  Went to complete integration steps, but upon the step that states to push button on Sync for 3 seconds until light flashes green repeatedly fails with "unexpected error".  Have repeated muliple times with the same result.

![image](https://user-images.githubusercontent.com/55962781/98429495-f4c86100-2074-11eb-9ee1-1bc808a55cfa.png)

HA log shows the following:

![image](https://user-images.githubusercontent.com/55962781/98429514-145f8980-2075-11eb-9f86-f6cfd0224c2a.png)

And the full log error:

![image](https://user-images.githubusercontent.com/55962781/98429581-77512080-2075-11eb-9590-b8cc6275b2fa.png)

**Comment by Resinchem** [comment]
Additional information, if helpful.  Upgraded HA to 0.117.5 with no change in error message.  Sync box is assigned static IP address and can be pinged from HA server (and all other machines on the network).  No VLANs or any other unusual network configs.  Sync box works fine via Hues app (I've had Sync box since release).  I've been watching the development of this add-on anxiously for a while now, waiting until it was available via HACS, so if there is any other information that I can provide please don't hesitate to let me know.

**Comment by vanlooverenkoen** [comment]
I am having the same problem. I did a factory reset of my sync box. No luck

**Comment by vanlooverenkoen** [comment]
I just downgraded to 1.7 and after that I was able to connect

**Comment by Resinchem** [comment]
Thanks!  I can confirm that dropping back to 1.7 allowed me to successfully complete the integration steps.

**Comment by EisernUnion** [comment]
Yes, got the same problem.... 1.7. works

**Comment by mvdwetering** [comment]
Yeah, sorry about that. The logging I added to diagnose an issue throws an error in the linking flow (which I thought I tried, but appaerently not)

v1.9 fixes this.
