### ISSUE TITLE
function syncronization is performed 

### ISSUE THREAD

**Issue by jrspowers** [mvdwetering/huesyncbox#14]
Hello

I am looking for a way to only switch off the lamp in the app mentions this function synchronization is performed and there a button long stop / start? would there be something possible to put this function in the media player? so if you're already doing the intensity? and then eg synchronization is performed as name? under there choices between play or stop, for example? I now do it via the app itself, but are it as handy as this can be done in the home assistant via the media player?

thanks in advance
greetings jrspower

**Comment by mvdwetering** [comment]
I am not sure what your question is, I need a better description.

Since you are talking about the app (mobile Hue Sync app I assume) maybe add a screenshot to make it more clear what function you are talking about.
And you seem to be talking about the mediaplayer card in HA, maybe also there a screenshot helps with some annotations.

**Comment by jrspowers** [comment]
hello 

I mean this function in the philips hue sync box app see photo !start function![image](https://user-images.githubusercontent.com/60328474/99191134-f7107680-276a-11eb-8db7-8ea9b79e6a0b.jpeg)stop function[image](https://user-images.githubusercontent.com/60328474/99191104-c8929b80-276a-11eb-8366-bfba6dd782f5.jpeg)this function calls ready for synchronization and it says next to start / stop button see photo & would like to see this function in the mediaplayer on home assistant see photo ![image](https://user-images.githubusercontent.com/60328474/99191157-16a79f00-276b-11eb-8d21-f5f2162f56a9.jpeg)where i mean hopefully you can  so further wall would be handy?

Greetings jrspower

**Comment by mvdwetering** [comment]
You can use the play/pause button in the mediaplayer card to start/stop syncing. 
Is that what you are looking for?

Note that the mediaplayer card is controlling the syncbox, not what is playing video/audio through the syncbox.

For now I have also mapped a few actions onto normal mediaplayer functionality to easily control the syncbox from the frontend. Eventually I would like to have a custom syncbox card which exposes the functionality in a clearer way, but I am not very comfortable with frontend development and I personally don't really need it so it is very low on the list.

FYI these are the mappings that currently are available (mediaplayer - syncbox):
play/pause - start/stop
volume - brightness
prev/next track - prev/next syncmode video/music/game
soundmode - intensity

**Comment by jrspowers** [comment]
hello 

thank you that is the function I was looking for & would be very useful if there is a special card for the hue sync box that shows it clearly and nice and all but this work also perfect although it is not so clear but very nice work thanks

Greetings jrspower

**Comment by mvdwetering** [comment]
This seemed to be resolved so closing it
