### ISSUE TITLE
HomeKit 

### ISSUE THREAD

**Issue by pilot1981** [mvdwetering/huesyncbox#21]
Hi,
I would obtain an object to enable syncing light using HomeKit scenes.

I have to create a. Ew switch/services? Which one?

**Comment by mvdwetering** [comment]
Since you [also asked on the HA forums](https://community.home-assistant.io/t/philips-hue-play-hdmi-sync-box-integration/204772/36) and I think it is a better place for such questions I answered there and will close this issue.
