### ISSUE TITLE
Show which input is detecting signal in attributes

### ISSUE THREAD

**Issue by franeko** [mvdwetering/huesyncbox#22]
**Is your feature request related to a problem? Please describe.**
I have a chromecast connected to the sync box. The chromecast is always on and always provides HDMI signal to the box. Thus, I the input switching options provided by the Sync Box don't work properly - it'll never switch from Chromecast to something else.

**Describe the solution you'd like**
I would like to create HA automatons for switching inputs. To do that I would like an option to see which inputs are providing HDMI signal. This Information is available in the app: when the sync box is on, for each input you can see one of three options:
1. No HDMI input detected
2. No signal detected.
3. HDMI Input detected
I would like to have this information available as the attributes.

**Describe alternatives you've considered**
An alternative for me is to:
1. Use HA automation for switching inputs to/from chromecast when I know if the chromecast is playing/idle
2. Use Sync Box built in automations for other inputs
It's ugly, complicated and I can't work it out properly (yet).

**Comment by mvdwetering** [comment]
The API seems to provide the info as unplugged, plugged, linked.
Linked seems to indicate there is a signal on the HDMI.

I could expose this info as attributes. E.g. input1.status, input2.status etc...

Would that be suitable for your needs?

**Comment by franeko** [comment]
Sound great! This improvement should fix my issues :)

Thanks a lot!

**Comment by mvdwetering** [comment]
I have added attributes for the 4 HDMI port and also added Device Triggers and Conditions for the status. Sorry for the long delay.

Did not make a release yet as I want to wait until next HA version is released next Wednesday to see if something pops up. If you want to try already you can select "Show beta versions" in HACS and then you can install the master branch which has these changes (manually download the zip from the master branch on Github).

**Comment by franeko** [comment]
Thanks a lot! Don't mind the time, it's amazing that you took your time to implement it :)

I'll wait couple more days for the stable version and let you know

**Comment by franeko** [comment]
Hi @mvdwetering !

When is the new release coming?

**Comment by mvdwetering** [comment]
I just made the 1.14.0 release which contains this new feature. I had some (unrelated) challenges when upgrading my HA which caused it to get shifted out a bit.

**Comment by franeko** [comment]
Michel - THANK YOU A LOT!

This seems to work really well.

One thing I noticed is that `linked ` state is available only when the device wakes up. When I put it to sleep it changes to `plugged`. I'm assuming it's what the box exposes and can't be fixed. Am I right?

**Comment by mvdwetering** [comment]
Yes, this information is forwarded directly from the box. I guess the part that figures out if there is a link gets disables when the box gets put to sleep.

**Comment by franeko** [comment]
Okay, thanks for the info

Michel van de Wetering ***@***.***> schrieb am So.,
19.09.2021 um 19:45:
