### ISSUE TITLE
Cannot Set Brightness via Script/Automation

### ISSUE THREAD

**Issue by brodkin** [mvdwetering/huesyncbox#25]
**Describe the bug**
Setting the brightness via the included service fails.

**To Reproduce**
1. Create a script or automation
2. Add "Call Service" action
3. Select "Philips Hue Play HDMI Sync Box: Set brightness"
4. Select brightness in UI or set via YAML

Only 0 and 1 can be selected as values and setting values via YAML does not work either.

**Expected behavior**
Brightness value of Hue Sync Box updated.

**Environment**
- Home Assistant Core version: core-2021.11.0
- Home Assistant operating environment (OS/Container/Supervised/Core): OS
- Huesyncbox integration version: 1.14.0

**Comment by mvdwetering** [comment]
Should be fixed in v1.15.0.

**Comment by brodkin** [comment]
Confirmed. Fixed!

Thank you!!!
