### ISSUE TITLE
Trouble with syncing with my actual hue sync box

### ISSUE THREAD

**Issue by metalcrue2k4** [mvdwetering/huesyncbox#29]
Hello,

I'm totally new with home assistant and I'm still learning and eager to learn too.  I had no trouble to install the huesyncbox addon and he did find my hue sync box and I was able to put to configured it into HA but he don't recognize any of the 4 HDMI config and I was wondering if I had to do this manually of it should sync everything from my box like the phillips hue lights system?

Thanks for all help you can provide,

Ghislain

**Comment by mvdwetering** [comment]
I am not exactly sure what you mean with "recognize any of the 4 HDMI config", but lets try to clarify it.

The HDMI ports are exposed as "sources" in the Mediaplayer. You can see on the card in the userinterface after pressing the ⋮ button (when the box is on, HA hides sources selection when device is off).

You can change sources though the user interface or through automations or service calls, but in that regard it is the same as any other mediaplayer that exposes sources.

**Comment by metalcrue2k4** [comment]
> I am not exactly sure what you mean with "recognize any of the 4 HDMI config", but lets try to clarify it.
> 
> The HDMI ports are exposed as "sources" in the Mediaplayer. You can see on the card in the userinterface after pressing the ⋮ button (when the box is on, HA hides sources selection when device is off).
> 
> You can change sources though the user interface or through automations or service calls, but in that regard it is the same as any other mediaplayer that exposes sources.

Hello it did work correctly after i follow up your instruction, pretty cool, thanks a lot

**Comment by mvdwetering** [comment]
Cleaning up some of the issues.
It seems this was resolved so closing it.
