### ISSUE TITLE
Failed to call service media_player/media_play. 16: Invalid State

### ISSUE THREAD

**Issue by COMASIGHT** [mvdwetering/huesyncbox#32]
Hi,
i'm new to HA but i've been through a few installations of HA and a few resets of the hue box.  i'm on a PI4 now but, each installation, i've received the following error while trying to turn of the sync setting:
Failed to call service media_player/media_play. 16: Invalid State
i am able to change inputs... 
any thoughts would be helpful
thanks

**Comment by mvdwetering** [comment]
I am not sure what is going on.

Could you provide a bit more detailed information on how or what you are doing? 
For example are you using the card in the dashboard, using device automations, calling a service or something else?
(and just to be sure, I assume the box is working fine with the normal sync app?)

It would also help if you could temporarily enable logging the `configuration.yaml` by adding the section below (or adding just the lines mentioning `huesyncbox` if the logging section already exits) and then reproduce the issue. After that you can disable the logging again.

```
logger:
  default: info
  logs:
    custom_components.huesyncbox: debug
    aiohuesyncbox: debug
```
