### ISSUE TITLE
brightness sensor 

### ISSUE THREAD

**Issue by jrspowers** [mvdwetering/huesyncbox#36]
hello 
I have a question wouldw it be possible for a sensor to make 
the brightness so that I can use it to see how much the brightness is ?

thank you in advance !

**Comment by mvdwetering** [comment]
Currently the brightness is mapped to the volume of the mediaplayer, so in that way you can see it right now.
And there is a service to control it (next to controlling it through volume).

I want to expose more controls/info as seperate entities in Home Assistant (like for example brightness, or the intensities) but that requires some changes in the internals so need to find some time to dedicate to that.

**Comment by mvdwetering** [comment]
Sorry, took a while. I just released v2.0.0 which includes a number entity (slider) for the brightness
