### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by insanelysick** [mvdwetering/huesyncbox#4]
Just installed this via HACS and after restarting and connecting this shows in the error log. Any ideas?

Traceback (most recent call last):
  File "/config/custom_components/huesyncbox/huesyncbox.py", line 34, in async_setup
    await self.async_update_registered_device_info() # Info might have changed while HA was not running
  File "/config/custom_components/huesyncbox/huesyncbox.py", line 81, in async_update_registered_device_info
    devices[0].id,
IndexError: list index out of range

Thanks

**Comment by insanelysick** [comment]
Just a quick update, I commented out "await self.async_update_registered_device_info()" in huesyncbox.py and its now working correctly.

**Comment by mvdwetering** [comment]
Ow, I see. That only works when you already have a box installed.
After building this I did not test with setting up my box again from scratch.
Lets get that fixed

**Comment by mvdwetering** [comment]
This should be fixed in v1.7
