### ISSUE TITLE
where to add the repository...

### ISSUE THREAD

**Issue by mcnahum** [mvdwetering/huesyncbox#5]
I guess I missing something...
can you clarify "Add this repository https://github.com/mvdwetering/huesyncbox to HACS as a "custom repository" with category "integration". This option can be found in the ⋮ menu"

I was thinking it was in Supervisor | Add-ON store and add from the menu but when I'm adding it here... it's bringing no option...

**Comment by mvdwetering** [comment]
That part of the installation instructions if for people using HACS (Home Assistant Community Store) which is a 3rd party integration for Home Assistant that allows easy install and updating of custom integrations, custom-cards and other things. See https://hacs.xyz for more info.

For the part you quoted you need to have HACS installed and setup and then:

1. Open the HACS management page from the sidebar
2. Select the Integrations section (can take a few seconds to appear)
3. Select the ⋮ menu at the top right

![image](https://user-images.githubusercontent.com/732514/94340344-45be5180-0001-11eb-811b-facae6293727.png)


If you do not use HACS you can install this custom component manually with the instructions a bit lower in the readme.

**Comment by mcnahum** [comment]
Thanks, it's working now..
HACS seams to not work correctly with Safari but it's ok with Chrome
