### ISSUE TITLE
Hue sync box connection

### ISSUE THREAD

**Issue by BigTadger** [mvdwetering/huesyncbox#50]
Anyone else notice that after a few hours or maybe half a day when using this integration the hue sync box goes unavailable and becomes totally unable to connect to my WiFi or even be found by the hue app until I totally reset it. I've had to do this for a couple days in a row now

**Comment by mvdwetering** [comment]
I havent seen or heard anything like that.
Btw what do you mean with total reset? I hope a powercycle, not needing to completely setup the box again?

My initial guess would be some networking issue as there is not a lot of other things going on, but would not really know where to start looking. 

I am assuming the syncbox software is up-to-date?
(it is configured for autoupdate by default I think so it most likely is, but cant hurt to check)

**Comment by BigTadger** [comment]
> I havent seen or heard anything like that. Btw what do you mean with total reset? I hope a powercycle, not needing to completely setup the box again?
> 
> My initial guess would be some networking issue as there is not a lot of other things going on, but would not really know where to start looking.
> 
> I am assuming the syncbox software is up-to-date? (it is configured for autoupdate by default I think so it most likely is, but cant hurt to check)

Yeah I need to do a full reboot and wipe it (restarting HA wifi or turning hue sync off and on doesn't work) it hasn't happened today but I will post logs next time it does happen its a rather weird thing. Could it be nest wifi not liking it maybe? Or the fact that its could be struggling to find the 2.4gh wifi in unsure tbh

**Comment by mvdwetering** [comment]
I have rebuild the integration from scratch with v2.0.0 and cleaning up some old issues.
Please open a new issue if this is still relevant on v2.0.0

**Comment by audiosnow** [comment]
I did not experience this issue prior to 2.0.0, but this exact problem has been occurring ever since the update to 2.0.0.
Rebooting HA and power cycling the sync box does not fix it. Deleting the device, resetting it within the Hue app, and re-adding the integration is the only repeatable solution.

**Comment by mvdwetering** [comment]
@audiosnow  That is really weird. Could you make a new issue and fill in the information in the template?
