### ISSUE TITLE
Dolby Vision compatibility - switch request

### ISSUE THREAD

**Issue by yashijoe** [mvdwetering/huesyncbox#51]
Thanks for this great integration
Once a while I need to switch on/off the Dolby Vision compatibility switch in the Hue app. That is a well know issue of the syncbox on some LCD.

Is there the chance you can include also this command in your great integration?
Thanks

**Comment by mvdwetering** [comment]
The integration needs some work before I can add other types off entities. I hope to be able to working on rewriting the addon to support this during the end of years holidays.
But after that it should be no problem to add it.

**Comment by yashijoe** [comment]
Thank you for the feedback

**Comment by mvdwetering** [comment]
Sorry, took a while. I just released 2.0.0 which includes a switch for the Dolby Vision compatibility settings.

**Comment by yashijoe** [comment]
Thank you!
Going to test it immediately
