### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by alexmace** [mvdwetering/huesyncbox#52]
I am trying to register the Sync Box: I've got the integration installed Home Assistant says that it's discovered the sync box, but when I click configure I get this:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/207391/210157716-bebc1d94-17f9-4bc2-8234-411c8aa3745f.png">

If I click submit, I get this:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/207391/210157739-cda3becd-7c7f-4229-9ca7-25a6d8dad149.png">

What am I missing?

**Comment by mvdwetering** [comment]
It seems that somehow the translation texts are not loaded.
Could you try to force refresh your browser, typically by pressing CTRL+F5 ?

**Comment by mvdwetering** [comment]
I have rebuild the integration from scratch with v2.0.0 and cleaning up some old issues.
Please open a new issue if this is still relevant on v2.0.0
