### ISSUE TITLE
HA warning for breaking change in 2024.8

### ISSUE THREAD

**Issue by kuges** [mvdwetering/huesyncbox#80]
Logger: homeassistant.data_entry_flow
Source: data_entry_flow.py:765
First occurred: 10:30:35 AM (1 occurrences)
Last logged: 10:30:35 AM

custom_components.huesyncbox.config_flow::ConfigFlow calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author

**Comment by mvdwetering** [comment]
Thanks for the reminder. I did see the deverloper blogpost about it, but did not have time yet to implement the change.

**Comment by mvdwetering** [comment]
Ow, it autocloses the issue if it gets mentioned in a PR that gets then merged.

So while it is fixed it will only be available in next release (got a few more things I want to put in).
