### ISSUE TITLE
Fails to connect after updating to Python 3.12

### ISSUE THREAD

**Issue by syphernl** [mvdwetering/huesyncbox#81]
**Describe the bug**
After upgrading from Python 3.11 to Python 3.12 this integration fails to load.

**To Reproduce**
1. Upgrade to Python 3.12

**Logging**
After enabling debug I see:

```
2024-04-03 20:37:51.112 DEBUG (MainThread) [aiohuesyncbox.huesyncbox] get, https://_192.xxx.xxx.xxx:443/api/v1, None
```

For some reason the URL it accesses has an underscore in front probably causing it to fail. Loading this (without underscore) works fine in my browser.

**Environment**
Provide details about the versions you are using, which helps to reproduce and find the issue quicker.

- Home Assistant Core version: 2024.3.2
- Home Assistant operating environment (OS/Container/Supervised/Core): Core
- Huesyncbox integration version: 2.0.1
- Last working version (if known): 2.0.1

Alpine 3.19.2 / Python 3.12.2 (via `pyenv`)

**Comment by mvdwetering** [comment]
The underscore is intended to be there, it will get translated a bit later. I should get that printed better to avoid confusion.

It would be unlikely to be just the Python 3.12 update. I am running Home Assistant OS which had Python 3.12 for 2 months already. It also works on my dev environment with Python 3.12 which is also a core install.

I am a bit stumped as all errors should log something and I am not sure how to get more detailed logging.

Do you see any other errors?

**Comment by syphernl** [comment]
This is the only thing it outputs in `home-assistant.log`. Nothing else in the internal logs.
The integration itself complains about "error requesting data from ....."

I have some problems with another (built-in) integration as well, which mentions something about SSL. Could be related to this, seeing the syncbox is reached over SSL.

**Comment by mvdwetering** [comment]
Sorry for the delay. Since there are no real leads I added more logging and created a new release with the extra logging. 

When using HACS you can enable the beta release toggle for this integration and it should become visible as "v2.1.0a0".

If you install manually grab it here: 
https://github.com/mvdwetering/huesyncbox/releases/tag/v2.1.0a0

**Comment by syphernl** [comment]
No worries!

Due to this issue (and another core integration with similar problems) I have decided to migrate to HAOS instead. After this everything is working fine again so I guess we can consider this issue resolved.

Thanks :)
